name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  local_data_source:
    path: ../local_data_source
  equatable: ^2.0.5
  uuid: ^4.4.2

