name: key_manager
description: Dart package which manages the keys.
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  hex: ^0.2.0
  basic_utils: ^5.7.0

